ALTER TABLE books ADD COLUMN IF NOT EXISTS page_count INTEGER;
ALTER TABLE book_reads ADD COLUMN IF NOT EXISTS page_count INTEGER;
ALTER TABLE book_reads ADD COLUMN IF NOT EXISTS page_count_confirmed BOOLEAN NOT NULL DEFAULT FALSE;